# Generated by Django 4.1.13 on 2024-04-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vacant_descripcion_vacant_nom_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacant',
            name='url_empresa',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='vacant',
            name='url_vacante',
            field=models.URLField(default=''),
        ),
    ]
