# Generated by Django 4.1.13 on 2024-05-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vacant_url_empresa_vacant_url_vacante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacant_report',
            fields=[
                ('vacant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.vacant')),
                ('Report', models.TextField()),
                ('verification', models.BooleanField(default=False)),
            ],
            bases=('main.vacant',),
        ),
    ]
