# Generated by Django 4.1.13 on 2024-05-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vacant_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacant_report',
        ),
    ]
