# Generated by Django 4.1.13 on 2024-05-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_vacant_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacant_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_envio_c', models.DateField(null=True)),
                ('Correo_dest_c', models.EmailField(blank=True, max_length=254)),
                ('Correo_org_c', models.EmailField(blank=True, max_length=254)),
                ('Titula_c', models.CharField(max_length=120)),
                ('telefono_c', models.CharField(default='', max_length=13)),
                ('nom_empresa_c', models.CharField(default='', max_length=60)),
                ('descripcion_c', models.TextField(default='')),
                ('texto_t_c', models.TextField(default='')),
                ('url_vacante_c', models.URLField(default='')),
                ('url_empresa_c', models.URLField(default='')),
                ('Report', models.TextField()),
                ('verification', models.BooleanField(default=False)),
            ],
        ),
    ]
