# Generated by Django 4.1.13 on 2024-05-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vacant_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vacant',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacant_report',
            name='state_c',
            field=models.BooleanField(default=False),
        ),
    ]
