# Generated by Django 4.1.13 on 2024-05-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_admin_vacant_state_vacant_report_state_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='vacants_wait',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
